version: '3.7'

services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: ncr-2019-global-hackathon-server
    container_name: server
    networks:
      - backend
    volumes:
      - ./server:/usr/src/server
    ports:
      - 5000:5000
    environment:
      FLASK_ENV: ${FLASK_ENV}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}

  database:
    image: postgres:11
    container_name: database
    networks:
      - backend
    ports:
      - 5432:5432
    volumes:
      - ./build/db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

networks:
  backend:
